### ISSUE TITLE
Class 'Billplz\Laravel\BillplzServiceProvider' not found

### ISSUE THREAD

**Issue by dan1661** [jomweb/billplz-laravel#5]
- Library Version: #.#.#
- API Version: v#
- Laravel Version: #.#.#
- PHP Version: #.#.#

### Description:
getting error after fresh install: Class 'Billplz\Laravel\BillplzServiceProvider' not found

I notice there is no public function boot() in BillplzServiceProvider. could this be the problem?

**Comment by crynobone** [comment]
If the class doesn't exist the tests that this repo run every day should has failed by now.
